Spanish translation
jixxed/ed-odyssey-materials-helper pull request #383
Opened 2024-08-10 11:30 UTC by Cashiot

Further spanish translation to match the game content

2024-08-10 20:37 UTC, jixxed commented on application/src/main/resources/locale/blueprint/horizons/description.csv
> +blueprint.description.horizons.engineer_a3c_unlock,Initial contract: 25 units of Sensor Fragments.,Initial contract: 25 units of Sensor Fragments.,Erstvertrag: 25 Einheiten von Sensorfragmenten.,"Con
oddly many double quotes in here

2024-08-10 20:39 UTC, jixxed commented on application/src/main/resources/locale/blueprint/horizons/description.csv
> +blueprint.description.horizons.engineer_a3c_unlock,Initial contract: 25 units of Sensor Fragments.,Initial contract: 25 units of Sensor Fragments.,Erstvertrag: 25 Einheiten von Sensorfragmenten.,"Con
looks like it also happened in a previous PR

2024-08-10 20:43 UTC, jixxed requested changes
please check the double quotes

2024-08-10 22:17 UTC, Cashiot commented
I think that should be sorted out by now. Only one word has been left in quotation marks because that is how it appears in the original description.

I don't think that's the case, but I don't know if I've deleted something that made sense in other languages, because it wasn't only Spanish that had these problems.

2024-08-11 09:11 UTC, merged

2024-08-11 09:12 UTC, jixxed commented
thnx for checking 👍